# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and build
        run: |
          npm install
      - name: Format check
        run: |
          npm run format-check
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm test
      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: tiny-virtual-dom-codecov
          fail_ci_if_error: true
          verbose: true
# TODO: using ncc when packaging
